export interface Artwork {
  id: string;
  title: string;
  year: number;
  medium: string;
  imageSrc: string;
  blurDataUrl: string;
  width: number;
  height: number;
  description?: string;
}

// Placeholder blur data URL (tiny gray placeholder)
const placeholderBlur =
  "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAIAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAUH/8QAIhAAAgEDBAMBAAAAAAAAAAAAAQIDBAURAAYSITFBUWH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABkRAAIDAQAAAAAAAAAAAAAAAAECABEhMf/aAAwDAQACEQMRAD8AzCw2+3z7etdTVVDLNLVSL5AChY+gM9aU/wBo3f/Z";

// Finished artwork for the main gallery
export const finishedArtwork: Artwork[] = [
  {
    id: "artwork-17",
    title: "Process Book Spread",
    year: 2026,
    medium: "Process Book Spread",
    imageSrc: "/images/gallery/process-book-spread.png",
    blurDataUrl: placeholderBlur,
    width: 5100,
    height: 3300,
  },
  {
    id: "artwork-7",
    title: "UCDA Poster Competition",
    year: 2026,
    medium: "Digital Poster",
    imageSrc: "/images/gallery/horizon.png",
    blurDataUrl: placeholderBlur,
    width: 3600,
    height: 5400,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-8",
    title: "Pinto Beans",
    year: 2026,
    medium: "Digital Poster",
    imageSrc: "/images/gallery/beans.png",
    blurDataUrl: placeholderBlur,
    width: 3300,
    height: 5100,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-12",
    title: "Jack Johnson Poster",
    year: 2025,
    medium: "Digtial Illustration",
    imageSrc: "/images/gallery/Project1JJ.jpg",
    blurDataUrl: placeholderBlur,
    width: 2250,
    height: 3300,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-13",
    title: "Freedom of Taste",
    year: 2025,
    medium: "Digtial Illustration",
    imageSrc: "/images/gallery/FOT.png",
    blurDataUrl: placeholderBlur,
    width: 5400,
    height: 7200,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-15",
    title: "State of America",
    year: 2025,
    medium: "Digtial",
    imageSrc: "/images/gallery/USA.png",
    blurDataUrl: placeholderBlur,
    width: 5992,
    height: 7984,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-14",
    title: "Dissection",
    year: 2025,
    medium: "Digtial",
    imageSrc: "/images/gallery/Dissection.png",
    blurDataUrl: placeholderBlur,
    width: 3600,
    height: 5400,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-1",
    title: "Angel",
    year: 2026,
    medium: "Illustration",
    imageSrc: "images/gallery/angel.jpg",
    blurDataUrl: placeholderBlur,
    width: 2269,
    height: 3416,
    description: "a nice card.",
  },
  {
    id: "artwork-9",
    title: "Hunting Island",
    year: 2026,
    medium: "Illustration",
    imageSrc: "/images/gallery/lineup_comic2.jpg",
    blurDataUrl: placeholderBlur,
    width: 12150,
    height: 4800,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-10",
    title: "Sprouting Spring 1",
    year: 2026,
    medium: "Illustration",
    imageSrc: "/images/gallery/Flower1.gif",
    blurDataUrl: placeholderBlur,
    width: 2400,
    height: 2400,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-11",
    title: "radish/beet",
    year: 2026,
    medium: "Illustration",
    imageSrc: "/images/gallery/radish_beet_copy.png",
    blurDataUrl: placeholderBlur,
    width: 1756,
    height: 2691,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-5",
    title: "Minis",
    year: 2025,
    medium: "Digital Painting",
    imageSrc: "/images/gallery/minis.jpg",
    blurDataUrl: placeholderBlur,
    width: 1170,
    height: 1213,
  },
  {
    id: "artwork-3",
    title: "Clay Dogs",
    year: 2025,
    medium: "3D Render",
    imageSrc: "/images/gallery/claydogs.png",
    blurDataUrl: placeholderBlur,
    width: 751,
    height: 787,
  },
  {
    id: "artwork-2",
    title: "Blob",
    year: 2025,
    medium: "Water Color",
    imageSrc: "/images/gallery/blob.png",
    blurDataUrl: placeholderBlur,
    width: 648,
    height: 734,
    description: "Abstract interpretation of city architecture.",
  },
  {
    id: "artwork-6",
    title: "Face Remade",
    year: 2025,
    medium: "Mixed Media on Paper",
    imageSrc: "/images/gallery/remade_face.jpg",
    blurDataUrl: placeholderBlur,
    width: 3021,
    height: 3018,
    description: "Combining traditional weaving with contemporary painting.",
  },
  {
    id: "artwork-4",
    title: "Cookie Bird",
    year: 2025,
    medium: "Glazed Ceramic",
    imageSrc: "/images/gallery/paper6.JPG",
    blurDataUrl: placeholderBlur,
    width: 1440,
    height: 1920,
    description: "Hand-thrown pottery with custom glazes.",
  },
  {
    id: "artwork-16",
    title: "Moody Shapes",
    year: 2026,
    medium: "Mixed Media",
    imageSrc: "/images/gallery/moody-shapes.png",
    blurDataUrl: placeholderBlur,
    width: 2000,
    height: 1480,
  },
];

// Sketches and work-in-progress for the Sketchbook page
export const sketchbookArtwork: Artwork[] = [
  {
    id: "sketch-1",
    title: "Portraits of Sillies",
    year: 2024,
    medium: "Markers",
    imageSrc: "/images/sketchbook/sillies.jpg",
    blurDataUrl: placeholderBlur,
    width: 3057,
    height: 1542,
  },
  {
    id: "sketch-2",
    title: "Swimmers+Plants",
    year: 2024,
    medium: "Markers",
    imageSrc: "/images/sketchbook/s+p(sizegood).jpg",
    blurDataUrl: placeholderBlur,
    width: 3057,
    height: 1542,
  },
  {
    id: "sketch-3",
    title: "Portraits",
    year: 2024,
    medium: "Ink+Pastels",
    imageSrc: "/images/sketchbook/portraits.gz.jpg",
    blurDataUrl: placeholderBlur,
    width: 3095,
    height: 2412,
  },
  {
    id: "sketch-4",
    title: "Portraits",
    year: 2024,
    medium: "Paintpen and Graphite",
    imageSrc: "/images/sketchbook/studyingpagegs.jpg",
    blurDataUrl: placeholderBlur,
    width: 3071 ,
    height: 2500,
  },
  {
    id: "sketch-5",
    title: "Graphite Portraits",
    year: 2024,
    medium: "Graphite",
    imageSrc: "/images/sketchbook/pencilpicsgoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 3099,
    height: 2500,
  },
  {
    id: "sketch-6",
    title: "Clowning Around",
    year: 2024,
    medium: "Graphite and Markers",
    imageSrc: "/images/sketchbook/ClowningAroundgoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 3096,
    height: 2434,
  },
  {
    id: "sketch-7",
    title: "Wow this is Nice",
    year: 2024,
    medium: "Markers",
    imageSrc: "/images/sketchbook/wowthisisnice.jpg",
    blurDataUrl: placeholderBlur,
    width: 2952,
    height: 1462,
  },
  {
    id: "sketch-8",
    title: "THANKS",
    year: 2024,
    medium: "Ink",
    imageSrc: "/images/sketchbook/thanksgoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 3043,
    height: 2376,
  },
  {
    id: "sketch-9",
    title: "Stained.",
    year: 2024,
    medium: "Ink",
    imageSrc: "/images/sketchbook/stainedgoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 3109,
    height: 2415,
  },
  {
    id: "sketch-10",
    title: "Posh People",
    year: 2024,
    medium: "Oil Pastels",
    imageSrc: "/images/sketchbook/poshpeoplegoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 2422,
    height: 3087,
  },
  {
    id: "sketch-11",
    title: "People",
    year: 2024,
    medium: "Ink",
    imageSrc: "/images/sketchbook/peoplegoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 3114,
    height: 2440,
  },
  {
    id: "sketch-12",
    title: "Peek",
    year: 2025,
    medium: "Markers",
    imageSrc: "/images/sketchbook/peekgoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 3033,
    height: 1490,
  },
  {
    id: "sketch-13",
    title: "Greg and People",
    year: 2025,
    medium: "Markers and Pen",
    imageSrc: "/images/sketchbook/greggoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 3037,
    height: 2418,
  },
  {
    id: "sketch-14",
    title: "Faces",
    year: 2025,
    medium: "Gouache and Pen",
    imageSrc: "/images/sketchbook/facesgoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 2998,
    height: 1476,
  },
  {
    id: "sketch-15",
    title: "Sad People?",
    year: 2025,
    medium: "Markers and Pen",
    imageSrc: "/images/sketchbook/endgoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 3033,
    height: 1500,
  },
  {
    id: "sketch-16",
    title: "I Don't Draw Hands",
    year: 2024,
    medium: "Ink",
    imageSrc: "/images/sketchbook/dontgoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 1560,
    height: 2414,
  },
  {
    id: "sketch-17",
    title: "Brother has a Beard",
    year: 2024,
    medium: "Ink",
    imageSrc: "/images/sketchbook/brotherbeardgoodsize.jpg",
    blurDataUrl: placeholderBlur,
    width: 3139,
    height: 2420,
  },
  {
    id: "sketch-18",
    title: "Bird Look",
    year: 2025,
    medium: "Gouache",
    imageSrc: "/images/sketchbook/BirdLook.jpg",
    blurDataUrl: placeholderBlur,
    width: 3010,
    height: 1469,
  },
];

// Helper functions
export function getFinishedArtwork(): Artwork[] {
  return finishedArtwork;
}

export function getSketchbookArtwork(): Artwork[] {
  return sketchbookArtwork;
}

export function getArtworkById(id: string): Artwork | undefined {
  return [...finishedArtwork, ...sketchbookArtwork].find(
    (artwork) => artwork.id === id
  );
}
